# version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Maps port 3000 on the host to port 80 in the container
    restart: always
   
